### ISSUE TITLE
Location Permissions on Apple Silicon always return Undetermined

### ISSUE THREAD

**Issue by jminutaglio** [sparrowcode/PermissionsKit#259]
**Describe the bug**
When running an iOS app on a Mac (Apple Silicon), location returns undetermined when location permissions are grated.

EX:
when `ProcessInfo.processInfo.isiOSAppOnMac` is `true`
& location is allowed

Both:
```
SPPermissions.Permission.locationWhenInUse.notDetermined
SPPermissions.Permission.locationAlways.notDetermined
```

are `true`

In this state, the UI is correctly showing the location permission is allowed.

**Smartphone (please complete the following information):**
 - iOS Version 14+ running on Mac w/ Apple Silicon
 - Framework Version 6.6.3+
 - Installed via Cocoapods

**Comment by ivanvorobei** [comment]
I have checked it, and can share some info. 

I full confirm behaviour that you describe, really bug. I see if set delay even zero, new state with same request changed. I think it some special logic for location center for Mac catalyst. For now I can't add ant solution because its catalyst bug. 

I leave issue open for observe it. You can set zero delay and request valid states for now like temp solution.

**Comment by jminutaglio** [comment]
For clarity, I'm referring to the behavior on iOS App on Mac, not Mac Catalyst.

iOS App on Mac defined as:
```
// Swift
var isiOSAppOnMac = false
if #available(iOS 14.0, *) {
    isiOSAppOnMac = ProcessInfo.processInfo.isiOSAppOnMac
}
print("\(isiOSAppOnMac ? "iOS app on Mac" : "not iOS on Mac")!")
```

Not Catalyst:
```
#if targetEnvironment(macCatalyst)
    print("UIKit running on macOS")
#else
    print("Your regular code")
#endif
```

As a workaround are you saying a delay such as this would work? 
```

//state check
let state = [SPPermissions.Permission.camera, SPPermissions.Permission.photoLibrary, SPPermissions.Permission.mediaLibrary, SPPermissions.Permission.locationWhenInUse]
    
DispatchQueue.main.asyncAfter(deadline: .now() + 0.0) {let permissions = state.filter { $0.notDetermined }}

```

**Comment by ivanvorobei** [comment]
Same for iOS app on Mac. 

yes, async will help

**Comment by ivanvorobei** [comment]
@jminutaglio maybe you can check how it going now? Maybe fixed?
