### ISSUE TITLE
 Icons do not show in AR template project

### ISSUE THREAD

**Issue by noah-z** [sparrowcode/PermissionsKit#275]
**Describe the bug**
I'm using SPPermissions in my project which is generated with Xcode Augmented Reality App template and the icons don't  show in my project.
So I new  some empty projects with Augmented Reality App template but the icons don't  show either.
**To Reproduce**
New a project with Augmented Reality App template (in iOS tab) and add SPPermissions.
Add this in viewDidAppear

> let permissions: [SPPermissions.Permission] = [.camera, .microphone]
        let controller = SPPermissions.dialog(permissions)
        controller.present(on: self)

**Smartphone (please complete the following information):**
 - iOS Version 15.1.1
 - Framework Version 6.8.4
 - Installed via Cocoapods
 - Xcode Version 13.1

**Additional context**
I tested with the app template, the icons show.
I think there may be something wrong with the ar template but I don't know where.

**Comment by ivanvorobei** [comment]
Weird. I Run with empty AR template, and it work for me.
I released `7.0` version some hours ago, try update please to latest.
<img width="1039" alt="Screenshot 2021-12-13 at 19 33 12" src="https://user-images.githubusercontent.com/10995774/145851279-e90f963d-d3a4-4d7a-8842-e2a6daf40a67.png">

**Comment by noah-z** [comment]
I updated to 7.0 and tested again.
With SPM, it works fine.
But with CocoaPods, still don't  show.
Could you try via CocoaPods let me know if it's my problem.
<img width="1445" alt="Screen Shot 2021-12-14 at 01 29 23" src="https://user-images.githubusercontent.com/9639371/145860693-d9c83720-03d2-4444-bcd0-5a1c9559b383.png">

**Comment by ivanvorobei** [comment]
Confirmed. I think something with bundle, but not sure for now. Checking.

**Comment by ivanvorobei** [comment]
I don't find any additional detail. Project is same like original empty project. Pods ignoring only images, not Text and other files. Look weird.

**Comment by xygkevin** [comment]
I have also encountered this problem, there is no problem running the project directly with Xcode, it is not displayed after packaging, I think it is because the resource file is not set correctly.

**Comment by xygkevin** [comment]
I recommend adding the icon's resource bundle to the project as a separate bundle rather than placing it in Assert as a folder

**Comment by xygkevin** [comment]
Check out the link below to see if it works or not

https://www.jianshu.com/p/66da0b4585c3

**Comment by rajaonah-toky** [comment]
> I don't find any additional detail. Project is same like original empty project. Pods ignoring only images, not Text and other files. Look weird.

I've got the same issue, and it appears only on testflight

**Comment by ivanvorobei** [comment]
I clean project and now its with new name. Also I see with AR template all sources work correctly. Let me know if need something else.

<img width="600" alt="Screenshot 2022-04-17 at 15 05 06" src="https://user-images.githubusercontent.com/10995774/163713563-2ee066d1-0df5-4f1e-a403-63fb6bace251.png">
