### ISSUE TITLE
Missing Features (NearBy + Network)

### ISSUE THREAD

**Issue by Droppix** [sparrowcode/PermissionsKit#280]
**Feature Description**
Hi,

Super framework, however 2 permissions are missing **NSNearbyInteractionUsageDescription** & **NSLocalNetworkUsageDescription**

Do you think you can bring them?
Thanks

**Comment by ivanvorobei** [comment]
Hello! 

`NSLocalNetworkUsageDescription` will request only by apple, but I know way to simulate it. If you can provide code for request and get state for both I can add shortly.

**Comment by Droppix** [comment]
Hi,

Thanks for your response.

You can try https://github.com/aniltaskiran/iOSNearbyInteraction, only you must add "NSNearbyInteractionUsageDescription" in info.plist.

Thanks

**Comment by ivanvorobei** [comment]
Moved to #282
