### ISSUE TITLE
Screen Record Permission

### ISSUE THREAD

**Issue by swatisrivs** [sparrowcode/PermissionsKit#284]
Hi ,

My app uses SPPermissions to take various permissions from user, now I want to take screen record permission as well.. Do u have anything for the.

Thanks

**Comment by ivanvorobei** [comment]
Hi! 
Can you provide code for request permission and check state?

**Comment by hanumanAbacus** [comment]
@ivanvorobei we need to add ability to add customise permissions by extension, if we can use struct instead of enum this can be easily achieved

**Comment by ivanvorobei** [comment]
> @ivanvorobei we need to add ability to add customise permissions by extension, if we can use struct instead of enum this can be easily achieved
> 
> 

It's available already. Check model permission like NotificationPermission, it's class. 

Whim using like API wrapper for speed up. 

P.s. why are you choose this issue to comment?

**Comment by swatisrivs** [comment]
Thanks for reaching out..my problem is solved..I was reinitializing windows
frame that was preventn permission.

Regards
Swati
