### ISSUE TITLE
Image Icon doesn't work when it's on testFlight, but work when I launch it from XCode,  SPPermissions/Core (7.1.5)

### ISSUE THREAD

**Issue by rajaonah-toky** [sparrowcode/PermissionsKit#285]
**Details**
 - iOS Version e.g. 15.3.1
 - Installed via Cocoapods
 
**Describe the Bug**
![274651841_661868938486884_2969705223783565633_n](https://user-images.githubusercontent.com/87367488/159215581-4f00da95-77b5-4183-82e8-e9368c094855.jpg)

Image Icon doesn't work when it's on testFlight, but work when I launch it from XCode, SPPermissions/Core SPPermissions/Core (7.1.5)

**Comment by ivanvorobei** [comment]
Hello, sorry for delay! 
Problem still here?

**Comment by ivanvorobei** [comment]
I see not, did test now. Let me know if need something other.
