### ISSUE TITLE
HomeKit Permission

### ISSUE THREAD

**Issue by ggoraa** [sparrowcode/PermissionsKit#286]
**Feature Description**
I can't find any mentioning of HomeKit permission in SPPermissions, I think it's missing, can you add it? Thanks in advance!

**Comment by ivanvorobei** [comment]
Hello, HomeKit doesn't supported by now

**Comment by ggoraa** [comment]
> Hello, HomeKit doesn't supported by now 

Understood, can you add support for it?

**Comment by ivanvorobei** [comment]
@ggoraa can you provide code for request permission?

**Comment by ggoraa** [comment]
> @ggoraa can you provide code for request permission? 

Sorry, unable to find any :(

Documentation says that it is automatically asked when a `HKHomeManager` (or something like that) is instantiated. So, possibly manually asking a permission is not needed 🤷‍♂️

**Comment by ivanvorobei** [comment]
@ggoraa yes, exactly. Maybe available way to trigger it, we can move it code to permission request. Same work for local network permission
