### ISSUE TITLE
Delegate method when user taps on "settings" or "cancel"

### ISSUE THREAD

**Issue by CavalcanteLeo** [sparrowcode/PermissionsKit#291]
When you deny, PermissionsKit show up a alert with 2 options:
"cancel" and "settings", you can change the text of settings using `deniedPermissionAlertTexts `

But I need to know if the user has tapped in some of these 2 buttons, and it's private

https://github.com/sparrowcode/PermissionsKit/blob/84ee165d34306d837cb80995de770be4726751c2/Sources/PermissionsKit/Services/PresenterService.swift#L42

https://github.com/sparrowcode/PermissionsKit/blob/84ee165d34306d837cb80995de770be4726751c2/Sources/PermissionsKit/Models/Permission.swift#L56

Is there a way to detect that?

**Comment by ivanvorobei** [comment]
For now no way to detect it. In next version I am going to add it

**Comment by CavalcanteLeo** [comment]
amazing, thanks in advance

**Comment by ivanvorobei** [comment]
Closed because hasn't interface for now.
