### ISSUE TITLE
9.0.0 code missing

### ISSUE THREAD

**Issue by DigitalVanilla** [sparrowcode/PermissionsKit#299]
I just pulled the new version and everything is gone: delegate, dialogs, examples etc... everything.
What happen?

**Comment by ivanvorobei** [comment]
Hello! 


Framework focused on permissions. I dropped interface code, left only permission management. 
If you need it, use version `8.x.x`. 

In time I add new interfaces like other target.

**Comment by DigitalVanilla** [comment]
Ok, so is 8.x.x for now but you will add back all the UI in the 9.x.x in the future, got it.
Thanks!
