### ISSUE TITLE
Suggestion: add callback method to determine whether to authorize status

### ISSUE THREAD

**Issue by GPX-NSlog** [sparrowcode/PermissionsKit#307]
Steps to reproduce:
1. Open the app for the first time and request notification permission. Click Allow
2. Manually open the system settings page and turn off the App notification permission
3. Open the app again and request notification permission. Calling the request method will still take the request callback scheme

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/17864687/185539039-79dd9367-4282-42b9-ab65-24b9ee6f7101.png">

**Comment by ivanvorobei** [comment]
Got bug. will research it.

**Comment by lexuanquynh** [comment]
I think you should completion (granted, error)

**Comment by ivanvorobei** [comment]
It's stored by system. can't update it. same troubles with location, system not provide right data always
