### ISSUE TITLE
SPPermissions library has Adware inside!

### ISSUE THREAD

**Issue by kovallux** [sparrowcode/PermissionsKit#309]
I was surprised that my antivirus Bitdefender put to quarantine some files from this library, see screenshot https://drive.google.com/file/d/1sJbWRXOrOj4P-6NE_CaD-cietG84TSJ6/view?usp=sharing

**Comment by ivanvorobei** [comment]
It's funny. But all code is open, I see mail ware in build folder. So check your side. 

Also you can see all code in repository.
