### ISSUE TITLE
iOS 17: Migrating to the new Calendar access levels

### ISSUE THREAD

**Issue by DavidTiimo** [sparrowcode/PermissionsKit#316]
Hi,

Thank you for having a great repository.

I am working on the new Xcode beta 15 with iOS 17 and I am experiencing some issues with calendar access.
This is due to Apple introducing new levels of access to calendars.

Taken from one of Apples tech notes (https://developer.apple.com/documentation/technotes/tn3152-migrating-to-the-latest-calendar-access-levels):
_Xcode 15 includes SDKs for iOS 17, macOS 14, and watchOS 10 that introduce notable changes in EventKit such as new access levels: the ability to add events using EventKitUI without requesting access to Calendar, write-only access, and full access. Apps that don’t request access to calendar data use [EKEventEditViewController](https://developer.apple.com/documentation/eventkitui/ekeventeditviewcontroller) to present UI for editing an event, which the person using your app can save. See [Accessing the Event Store](https://developer.apple.com/documentation/eventkit/accessing_the_event_store) for details. If the user grants your app write-only access, your app can create and write calendar events. However, your app can’t read or delete any events from the user’s calendars, including the ones it creates. If the user grants your app full access, your app can read, write, create, and delete calendar events as in iOS 16 and earlier, for example. To learn how to update your app to use these new features, see [TN3152: Migrating to the latest Calendar access levels](https://developer.apple.com/documentation/technotes/tn3152-migrating-to-the-latest-calendar-access-levels)._

The current PermissionKit cannot access the calendar and cannot view events from the calendar.

The button has the "active"/"pressed" styling and on tap nothing will happen. 
![Simulator Screenshot - iPhone 14 Pro - 2023-07-18 at 14 51 19](https://github.com/sparrowcode/PermissionsKit/assets/126571760/ae879cba-10b3-4035-86db-773a174e33e5)

**Comment by ivanvorobei** [comment]
Hey! Actual version hasn't UI, so it's related to old versions
