### ISSUE TITLE
iOS 17: Migrating to the new Calendar access levels

### ISSUE THREAD

**Issue by ostatnicky** [sparrowcode/PermissionsKit#318]
As mentioned in https://github.com/sparrowcode/PermissionsKit/issues/316 (and not sure why it was closed without any interaction) iOS 17 has new API for calendar access.

```
eventStore.requestAccess
```
https://github.com/sparrowcode/PermissionsKit/blob/d10e48fb51a49b1a8db2a814ff7f7353415b72a3/Sources/CalendarPermission/CalendarPermission.swift#L54

should be replaced with new `requestFullAccessToEvents`.

So this PermissionKit will not work on iOS 17!

**Comment by alexanderpuchta** [comment]
@ostatnicky https://github.com/sparrowcode/PermissionsKit/pull/319 you can use my fork as long as this PR will be merged

**Comment by ostatnicky** [comment]
> @ostatnicky #319 you can use my fork as long as this PR will be merged

You're a legend!

**Comment by ivanvorobei** [comment]
@ostatnicky hey. You miss my response - last release don't have any UI, only logic of request permissions. So it's very old release. 

For now I see point of check it and shortly confirm PR.

**Comment by ivanvorobei** [comment]
released v9.1.0 you can upgrade now. thanks for PR and info!

**Comment by ostatnicky** [comment]
Thank you very much!

**Comment by alexanderpuchta** [comment]
you're welcome guys!
