### ISSUE TITLE
ReminderPermission update with write-only access (iOS 17)

### ISSUE THREAD

**Issue by ostatnicky** [sparrowcode/PermissionsKit#322]
As we're working on the access levels for `CalendarPermission` on iOS 17, we should update `ReminderPermission` too.

The `ReminderPermission` update to iOS 17 full access was done in PR https://github.com/sparrowcode/PermissionsKit/pull/319.

Let's update it with write-only level too after PR https://github.com/sparrowcode/PermissionsKit/pull/320 is done.

**Comment by alexanderpuchta** [comment]
@ivanvorobei if you want to, you can assign this to me and I will provide solution for reminder too. I haven't seen that reminder has writeOnly too
