### ISSUE TITLE
SPPermissionsDataSource not found

### ISSUE THREAD

**Issue by rohan-59** [sparrowcode/PermissionsKit#327]
Installed latest version using SPM but getting error "Cannot find type 'SPPermissionsDataSource' in scope". I have added import PermissionsKit and all other permission import which are needed. 
 
Also few previous version functionalities like "dialog for multiple permission" is also missing.

**Comment by ivanvorobei** [comment]
Hello! Don't have any datasource and UI more. left only for old versions.
