### ISSUE TITLE
client implementation missing?

### ISSUE THREAD

**Issue by DiegoResnik** [sparrowcode/PermissionsKit#330]
Hi,

I've been using this library for years now.

I'm using cocapods, I understand you stopped supporting this - I guess that's why I didn't notice I was "stuck" with an old version.

I wanted to update to last version and when I pulled it using  package manager instead  I've noticed it was drastically changed

I used an object implementing SPPermissionsDelegate, SPPermissionsDataSource...but it seems to be changed now.

Can you refer me to a sample client app?

**Comment by ivanvorobei** [comment]
Hello! 

I still support Cocoapods, please check Readme. 

now I drop from project any UI. its only about request permissions.

**Comment by ivanvorobei** [comment]
Examples in readme as well

**Comment by DiegoResnik** [comment]
@ivanvorobei that's too bad, till what version the ui exists? are there any major issues using the last version with ui?

**Comment by ivanvorobei** [comment]
Celandar got changed with type request. Rest same so you can check releases and get last valid version.
