### ISSUE TITLE
LocationWhenInUsePermission is incompatible

### ISSUE THREAD

**Issue by yangdengxueshi** [sparrowcode/PermissionsKit#335]
`
[!] CocoaPods could not find compatible versions for pod "PermissionsKit/LocationWhenInUsePermission":
  In Podfile:
    PermissionsKit/LocationWhenInUsePermission (from `https://github.com/sparrowcode/PermissionsKit`)

None of your spec sources contain a spec satisfying the dependency: `PermissionsKit/LocationWhenInUsePermission (from `https://github.com/sparrowcode/PermissionsKit`)`.
`

**Comment by ivanvorobei** [comment]
Related to #332. Use `LocationPermission ` after 10x version.
