### ISSUE TITLE
New iOS 17 requestFullAccessToEvents returns always notDetermined on first run in Reminder

### ISSUE THREAD

**Issue by Monkey-X-Byte** [sparrowcode/PermissionsKit#340]
New iOS 17 requestFullAccessToEvents returns always notDetermined on first run in Reminder

**Comment by ivanvorobei** [comment]
No any bugs here 

<img width="1203" alt="Screenshot 2024-05-23 at 10 08 03" src="https://github.com/sparrowcode/PermissionsKit/assets/10995774/31887312-df77-4028-83c1-d2de4d847e30">
<img width="1289" alt="Screenshot 2024-05-23 at 10 08 09" src="https://github.com/sparrowcode/PermissionsKit/assets/10995774/478a61f7-d0a2-4214-b979-4bdb7776bb30">

**Comment by ivanvorobei** [comment]
Second launch as well 

<img width="1248" alt="Screenshot 2024-05-23 at 10 08 50" src="https://github.com/sparrowcode/PermissionsKit/assets/10995774/94470457-e92e-497d-ac0e-6c9107b2a6e1">
