### ISSUE TITLE
Permission.location(access: .always).request {}

### ISSUE THREAD

**Issue by luckycherry** [sparrowcode/PermissionsKit#342]
Permission.location(access: .always).request {}
The method is not invoking the callback correctly. It's returning the result immediately when the permission prompt appears

**Comment by luckycherry** [comment]
The permission prompt for iOS 14 iPhone 7's location permission pops up and immediately disappea

**Comment by ivanvorobei** [comment]
I don't see any problem here 

<img width="1095" alt="Screenshot 2024-05-23 at 09 54 38" src="https://github.com/sparrowcode/PermissionsKit/assets/10995774/dbe71538-8a73-498b-8828-59620ca4568d">
<img width="1133" alt="Screenshot 2024-05-23 at 09 54 47" src="https://github.com/sparrowcode/PermissionsKit/assets/10995774/573adc1e-69d8-4d34-a3b2-343ad3e7f7c3">

**Comment by luckycherry** [comment]
try :
                Permission.location(access: .whenInUse).request {
                    switch Permission.location(access: .whenInUse).status {
                    case .authorized:
                        Permission.location(access: .always).request {
                        }
                    default:
                        break
                    }
                }

**Comment by ivanvorobei** [comment]
> try : Permission.location(access: .whenInUse).request { // click Allow While Using App switch Permission.location(access: .whenInUse).status { case .authorized: Permission.location(access: .always).request { } default: break } }

please not doing spam. you report about callbacks, callbacks working well

**Comment by luckycherry** [comment]
I'm sorry.
I have found the solution. Because when setting the proxy, the locationManagerDidChangeAuthorization will immediately callback the result (at this time the result is wrong)
The simple and crude solution is to delay the request after setting the proxy, which can solve the problem.
add code in LocationAlwaysHandler:
![1716796052360](https://github.com/sparrowcode/PermissionsKit/assets/16411680/22987753-de70-4a43-a1a2-e01b167a3463)
