### ISSUE TITLE
Permission.location(access: .always).request {} bad 

### ISSUE THREAD

**Issue by luckycherry** [sparrowcode/PermissionsKit#343]
The normal flow is to first prompt for "whenInUse" and then prompt for "always"

Permission.location(access: .whenInUse).request { // choice "While Using App"
                    if Permission.location(access: .whenInUse).status == .authorized {
                        Permission.location(access: .always).request {
                            
                        }
                    }
                }

**Comment by ivanvorobei** [comment]
Please describe bug clear
