### ISSUE TITLE
React to permission changes

### ISSUE THREAD

**Issue by feelingsonice** [sparrowcode/PermissionsKit#346]
Is there a way to react to permission changes? I know the [`locationManagerDidChangeAuthorization`](https://developer.apple.com/documentation/corelocation/cllocationmanagerdelegate/locationmanagerdidchangeauthorization(_:))  method from the `CLLocationManagerDelegate` does this for location permissions but haven't been able to find the equivalent for other permission types.

**Comment by ivanvorobei** [comment]
After reuquest you can get handler. if you want observing changes — you shoud make custom solution
