### ISSUE TITLE
ITMS-90683: Missing purpose string in Info.plist

### ISSUE THREAD

**Issue by DrunkardSworder** [sparrowcode/PermissionsKit#347]
I used the "Location" feature in version 10.0.1 and added NSLocationWhenInUseUsageDescription to my info.plist file. However, when I packaged the project and submitted it to Testflight, I received an email from Apple stating ITMS-90683: Missing purpose string in Info.plist, indicating that I should add NSLocationAlwaysAndWhenInUseUsageDescription.

When I reverted the version back to 9.x, everything was OK. I would like to know if it is now necessary to add both keys to the plist, or if the email was triggered because Apple's machine review detected relevant code related to "Location".

**Comment by ivanvorobei** [comment]
You shoud add both keys to plist
